### ISSUE TITLE
More button doesn't appear

### ISSUE THREAD

**Issue by afern247** [NuPlay/ExpandableText#1]
Hi, the more button doesn't appear. This is how it looks:

![image](https://user-images.githubusercontent.com/34192856/150709739-44ee6391-5d8c-4a45-8bbb-c0162bee5af1.png)

Can you look into it please

**Comment by NuPlay** [comment]
I'll fix it ASAP

**Comment by NuPlay** [comment]
I fixed the bug and uploaded it to the test branch
Could you please test it?

If there is no problem, I will merge it into the main branch

**Comment by afern247** [comment]
It's still the same :/

Did you test it? The issue might be in my code after all

**Comment by NuPlay** [comment]
I checked it as a problem that occurs when the width of the view frame is insufficient (width: 200) or less

So I changed the calculation method, but if it still doesn't work

Could you please show me your code if possible?
